/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ExpensesIndexLazyImport = createFileRoute('/expenses/')()

// Create/Update Routes

const ExpensesIndexLazyRoute = ExpensesIndexLazyImport.update({
  path: '/expenses/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/expenses/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ ExpensesIndexLazyRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/expenses/"
      ]
    },
    "/expenses/": {
      "filePath": "expenses/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
